name: First Workflow
on: [push,workflow_dispatch]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: loading on server
        uses: actions/checkout@v3
      - name: install node js
        uses: actions/setup-node@v3
          with:
            node-version: 16
      - name: install all dependency
        run: npm ci
      - name: deploy
        run: npm start
